# Generated by Django 4.0.6 on 2025-12-23 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_cvusuario_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_oferta', models.TextField()),
                ('palabra1', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra2', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra3', models.CharField(blank=True, max_length=200, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Necesidad',
            fields=[
                ('id_necesidad', models.AutoField(primary_key=True, serialize=False)),
                ('texto_necesita', models.TextField()),
                ('palabra1', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra2', models.CharField(blank=True, max_length=200, null=True)),
                ('palabra3', models.CharField(blank=True, max_length=200, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
