# Generated by Django 4.0.6 on 2025-12-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_oferta_necesidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvusuario',
            name='linkedin_qr',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvusuario',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
